[package]
name = "deno_unsync"
version = "0.1.0"
edition = "2021"
authors = ["the Deno authors"]
license = "MIT"
repository = "https://github.com/denoland/deno_unsync"

[dependencies]
tokio = { version = "1", features = ["rt"] }

[lib]
name = "deno_unsync"
