name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dsherret/rust-toolchain-file@v1
    - run: rustup install nightly
    - run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu miri
    - name: Build
      run: cargo build --verbose
    - name: Format
      run: cargo fmt -- --check
    - name: Lint
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests (miri)
      run: cargo +nightly miri test
