name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dsherret/rust-toolchain-file@v1
    - name: Build
      run: cargo build
    - name: Format
      run: cargo fmt -- --check
    - name: Lint
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Test
      run: cargo test --verbose

  miri:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v4
    - run: rustup install nightly
    - run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu miri
    - name: Tests (miri)
      run: cargo +nightly miri test
